FROM python:3.7-slim

RUN apt-get clean && \
    apt-get update -y

RUN apt-get -y install nginx && \
    apt-get -y install python3-dev && \
    apt-get -y install build-essential

COPY ./ /app
WORKDIR /app
RUN pip install -r requirements.txt --src /usr/local/src
COPY nginx.conf /etc/nginx
RUN chmod +x ./start.sh
CMD ["./start.sh"]